// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvNLVRl9zkTyBh5MhQpc6_mDxPCSZtQWk',
    appId: '1:827709204105:web:dadeedf5dc7dd03276c858',
    messagingSenderId: '827709204105',
    projectId: 'chat-app-with-ai-42e34',
    authDomain: 'chat-app-with-ai-42e34.firebaseapp.com',
    storageBucket: 'chat-app-with-ai-42e34.firebasestorage.app',
    measurementId: 'G-S78TYHFV2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAidBtZ0OwXPhRoPvs_9OblZt5RZjS4iU0',
    appId: '1:827709204105:android:01c93886a71e1a3476c858',
    messagingSenderId: '827709204105',
    projectId: 'chat-app-with-ai-42e34',
    storageBucket: 'chat-app-with-ai-42e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6YvhxHUo1usrz4YH8O1aohotVhT5Gv4g',
    appId: '1:827709204105:ios:770937cc865b909f76c858',
    messagingSenderId: '827709204105',
    projectId: 'chat-app-with-ai-42e34',
    storageBucket: 'chat-app-with-ai-42e34.firebasestorage.app',
    iosBundleId: 'com.example.chatAppWithAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvNLVRl9zkTyBh5MhQpc6_mDxPCSZtQWk',
    appId: '1:827709204105:web:bd25b5cde85e35c376c858',
    messagingSenderId: '827709204105',
    projectId: 'chat-app-with-ai-42e34',
    authDomain: 'chat-app-with-ai-42e34.firebaseapp.com',
    storageBucket: 'chat-app-with-ai-42e34.firebasestorage.app',
    measurementId: 'G-RD7C2Z5CPR',
  );
}
